In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data/tmdb_top_rated_movies.csv")
df.head()

,movie_name,description,genre
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama, Crime"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama, Crime"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama, Crime"
3,Schindler's List,The true story of how businessman Oskar Schind...,"Drama, History, War"
4,12 Angry Men,The defense and the prosecution have rested an...,Drama

In [3]:
# check is there html tags present?
import re
pattern = re.compile("<.*?>")
def has_html_tags(text): 
    return bool(pattern.search(text))

In [4]:
df['description'].isnull().sum()

np.int64(1)

In [5]:
df.dropna(inplace = True)

In [6]:
df['description'].apply(has_html_tags).sum()

np.int64(0)

- No HTML tags are present

### Remove Punctuations and do lower casing

In [7]:
import string
punc_list = string.punctuation
def remove_punctuations(text): 
    text = text.lower()
    return text.translate(str.maketrans("" , "" , punc_list))

In [8]:
temp = "HI! My name is tipto. My age is 23. I have interest in ml,dl,nlp,llms."
remove_punctuations(temp)

'hi my name is tipto my age is 23 i have interest in mldlnlpllms'

In [9]:
df['description'] = df['description'].apply(remove_punctuations)

### Remove stop words

In [18]:
from nltk.corpus import stopwords

In [19]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tipto\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [24]:
eng_stopwords = set(stopwords.words('english'))
def remove_stop_words(text): 
    return " ".join([word for word in text.split() if word not in eng_stopwords])

In [26]:
df['description'] = df['description'].apply(remove_stop_words)

In [27]:
df.head()

,movie_name,description,genre
0,The Shawshank Redemption,imprisoned 1940s double murder wife lover upst...,"Drama, Crime"
1,The Godfather,spanning years 1945 1955 chronicle fictional i...,"Drama, Crime"
2,The Godfather Part II,continuing saga corleone crime family young vi...,"Drama, Crime"
3,Schindler's List,true story businessman oskar schindler saved t...,"Drama, History, War"
4,12 Angry Men,defense prosecution rested jury filing jury ro...,Drama